<a href="https://colab.research.google.com/github/vaishnavibilla07/K-NN-Classification-demo/blob/main/K_NN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('https://github.com/afrozchakure/Internity-Summer-Internship-Work/raw/master/Day19_Logistic_Regression_and_Knn_Classification/train.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
# Dropping columns which may not contribute much to our machine learning model
cols = ['Name','Ticket','Cabin']
df = df.drop(['Name', 'Ticket', 'Cabin'],axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB

In [ ]:
# Dropping rows having missing values
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Sex          712 non-null    object
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64
 6   Parch        712 non-null    int64
 7   Fare         712 non-null    float64
 8   Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB

In [ ]:
# dataset is reduced to 712 rows from 891, which means we are wasting data.
# So we preserve the data and make use of it as much as we can
# Convert Pclass, Sex, Embarked to columns in pandas and drop them after conversion
dummies = []
cols = ['Pclass','Sex','Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))

In [ ]:
titanic_dummies = pd.concat(dummies, axis=1)
titanic_dummies.head()

       1      2      3  female   male      C      Q      S
0  False  False   True   False   True  False  False   True
1   True  False  False    True  False   True  False  False
2  False  False   True    True  False  False  False   True
3   True  False  False    True  False  False  False   True
4  False  False   True   False   True  False  False   True

In [ ]:
df = pd.concat((df,titanic_dummies),axis=1)
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,1,2,3,female,male,C,Q,S
0,1,0,3,male,22.0,1,0,7.2500,S,False,False,True,False,True,False,False,True
1,2,1,1,female,38.0,1,0,71.2833,C,True,False,False,True,False,True,False,False
2,3,1,3,female,26.0,0,0,7.9250,S,False,False,True,True,False,False,False,True
3,4,1,1,female,35.0,1,0,53.1000,S,True,False,False,True,False,False,False,True
4,5,0,3,male,35.0,0,0,8.0500,S,False,False,True,False,True,False,False,True

In [ ]:
# Now that we converted Pclass, Sex, Embarked values into columns,
# we drop the redundant same columns from the dataframe
df = df.drop(['Pclass', 'Sex', 'Embarked'], axis=1)
df.head()

,PassengerId,Survived,Age,SibSp,Parch,Fare,1,2,3,female,male,C,Q,S
0,1,0,22.0,1,0,7.2500,False,False,True,False,True,False,False,True
1,2,1,38.0,1,0,71.2833,True,False,False,True,False,True,False,False
2,3,1,26.0,0,0,7.9250,False,False,True,True,False,False,False,True
3,4,1,35.0,1,0,53.1000,True,False,False,True,False,False,False,True
4,5,0,35.0,0,0,8.0500,False,False,True,False,True,False,False,True

In [ ]:
df.info()
# Here we find that age has lots of missing values

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Age          712 non-null    float64
 3   SibSp        712 non-null    int64
 4   Parch        712 non-null    int64
 5   Fare         712 non-null    float64
 6   1            712 non-null    bool
 7   2            712 non-null    bool
 8   3            712 non-null    bool
 9   female       712 non-null    bool
 10  male         712 non-null    bool
 11  C            712 non-null    bool
 12  Q            712 non-null    bool
 13  S            712 non-null    bool
dtypes: bool(8), float64(2), int64(4)
memory usage: 44.5 KB

In [ ]:
# interpolate() function will replace all the missing NaNs to interpolated values (median of all ages)
df['Age'] = df['Age'].interpolate()

In [ ]:
# Age is interpolated now with imputed new values.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Age          712 non-null    float64
 3   SibSp        712 non-null    int64
 4   Parch        712 non-null    int64
 5   Fare         712 non-null    float64
 6   1            712 non-null    bool
 7   2            712 non-null    bool
 8   3            712 non-null    bool
 9   female       712 non-null    bool
 10  male         712 non-null    bool
 11  C            712 non-null    bool
 12  Q            712 non-null    bool
 13  S            712 non-null    bool
dtypes: bool(8), float64(2), int64(4)
memory usage: 44.5 KB

In [ ]:
# Converting our dataframe from pandas to numpy
# And assigning input and output
X = df.values
y = df['Survived'].values

In [ ]:
# X has Survived values in it, which should be removed
# So we drop in numpy column which is the 1st column.
X = np.delete(X, 1, axis=1)

In [ ]:
# Now that we are ready with X and y,
# splitting the dataset for 70% Training and  30% test set using scikit model selection
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state = 0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 55, metric = 'minkowski', p = 2)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=55)

In [ ]:
# Predicting the test results
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6495327102803738